-- S4b slice 2 (#134): the directory sync checkpoint.
--
-- Records what a sync run DID, and it exists mainly for the run that did nothing.
-- A refused run and a no-op run both write zero rows to every other table, so
-- without this they are the same event — and the whole point of refusing a
-- misconfigured sync is that somebody notices. A refusal nobody can see is an
-- outage with extra steps.
--
-- `status` is the discriminator and carries exactly three values:
--   'completed' — the run applied its plan (possibly an empty one)
--   'refused'   — a scale guard fired; NOTHING was applied, in either direction
--   'failed'    — the enumeration or the apply threw; the run is incomplete
--
-- `refusedReason` is only meaningful for 'refused' and is the text the operator
-- reads. It is nullable rather than defaulted: an empty string would be a refusal
-- with no explanation, which is the shape this column exists to prevent.
CREATE TABLE "directory_sync_checkpoints" (
  -- IDENTITY, not `serial`: the sequence belongs to the column's lifecycle rather
  -- than being a separate object with its own ownership and GRANTs to keep in step.
  -- BIGINT because a sync writes a row per run forever and nothing here is cheaper
  -- for being narrow — this key is referenced by no other table, so widening it now
  -- costs nothing and later would be a table rewrite.
  "id"            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  -- INTEGER, deliberately, and NOT bigint. There is no `organizations` table: every
  -- neighbouring table (`roles`, `groups`, `principal_role_grants`, `document_acl`)
  -- carries `"orgId" INTEGER NOT NULL DEFAULT 1` with no foreign key. Widening it
  -- here alone would make this the one column that cannot be joined or compared
  -- without a cast, for a counter that will never approach 2.1 billion tenants.
  "orgId"         INTEGER NOT NULL DEFAULT 1,
  "provider"      TEXT NOT NULL,
  "status"        TEXT NOT NULL,
  "refusedReason" TEXT,
  -- Counts of what was actually applied, so an operator can tell a sync that
  -- changed nothing from one that was never asked to change anything.
  "usersCreated"       INTEGER NOT NULL DEFAULT 0,
  "usersDeactivated"   INTEGER NOT NULL DEFAULT 0,
  "groupsCreated"      INTEGER NOT NULL DEFAULT 0,
  "membershipsAdded"   INTEGER NOT NULL DEFAULT 0,
  "membershipsRemoved" INTEGER NOT NULL DEFAULT 0,
  "startedAt"     TIMESTAMPTZ(3) NOT NULL,
  "finishedAt"    TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

  -- Enforced in the database rather than the application: this table is read to
  -- decide whether a sync is overdue and whether the last one refused, so a typo'd
  -- status would make a refused run invisible to every query looking for one.
  CONSTRAINT "directory_sync_checkpoints_status_check"
    CHECK ("status" IN ('completed', 'refused', 'failed')),

  -- A refusal without a reason is not a refusal anyone can act on, and a reason on
  -- a completed run is a contradiction. Both directions, because the failure that
  -- matters is the first one and the second is how it gets introduced later.
  CONSTRAINT "directory_sync_checkpoints_reason_check"
    CHECK (
      ("status" = 'refused' AND "refusedReason" IS NOT NULL)
      OR ("status" <> 'refused' AND "refusedReason" IS NULL)
    )
);

-- The query this table exists to serve: "what did the last run for this provider
-- do?", asked by the operator view and by whatever decides a sync is overdue.
CREATE INDEX "directory_sync_checkpoints_org_provider_finished_idx"
  ON "directory_sync_checkpoints" ("orgId", "provider", "finishedAt" DESC);
